# CUDA
cuda_devices: '0'

# dataset
dataset:
  data_root: 'diamond_simplified/'
  augment_data: false
  max_faces: 2000

# model
load_model: '/content/drive/MyDrive/DL_diamond_cutting/MeshNet/ckpt/MeshNet_best.pkl'

# MeshNet
MeshNet:
  structural_descriptor:
    num_kernel: 64
    sigma: 0.2
  mesh_convolution:
    aggregation_method: 'Concat'  # Concat/Max/Average
