# CUDA
cuda_devices: '0'   # multi-gpu training is available

# dataset
dataset:
  data_root: 'diamond_simplified/'
  augment_data: true
  max_faces: 2024

# result
ckpt_root: 'ckpt/'

# MeshNet
MeshNet:
  structural_descriptor:
    num_kernel: 64
    sigma: 0.2
  mesh_convolution:
    aggregation_method: 'Concat'  # Concat/Max/Average

# train
lr: 0.0005
momentum: 0.9
weight_decay: 0.0005
batch_size: 16
max_epoch: 100 #150
milestones: [30, 60]
gamma: 0.1
